FROM node:16-alpine

WORKDIR /usr/src/server

RUN apk add --no-cache python3 git make build-base dumb-init
RUN ln -sf python3 /usr/bin/python

COPY . .
ENV NODE_ENV development

RUN npm config set update-notifier false
RUN npm install

EXPOSE 80
ENTRYPOINT [ "dumb-init", "npm", "run", "dev" ]